ibm-openbmc/phosphor-state-manager

bmc_state_manager.cpp
chassis_state_manager.cpp
configure.ac
host_state_manager.cpp

This addresses one part of SW471678 (bmc and chassis state management failures). Another PR will come for the network part.
Upstream commits:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/25020/3
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/25153/2
Due to this change being a workaround for a UBI related performance issue, this fix will not be upstreamed. UBI is going away after OP940.

SW471678: Op940 dbus timeout fix in SMGR

---

bmc_state_manager.cpp

Per our circuit designer, a 0 actually is what indicates a pinhole
reset. My testing was in simulation so I was able to falsely test
my thinking of how the hardware behaved.
There is also still an ongoing discussion on why some machines show the
inverse of this logic but the circuit designer assures me that a 1 is
the default and indicates the reboot was not a pinhole reset and a 0
indicates it was a pinhole reset.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: I24e536e2dcb8b3263f4fa407bc6f91fdef3ae0ad

correct logic on detecting a pinhole reset

---

host_reset_recovery.cpp

If the host is then started, CFAM reset will start so FSI needs to be
scanned again, otherwise FSI access is broken.

Stop FSI scan service if chassis power on but host not booting

---

chassis_state_manager.cpp
chassis_state_manager.hpp

When power was on before a BMC reboot and system is now off, the host
sensors need to be reset to show the correct system state of `off` now.
This is done by starting the `phosphor-reset-sensor-states@0.service`
unit, which handles setting the appropriate dbus properties.
Tested:
Power on system and then remove/add AC
Check BootProgress, etc.. properties set by reset service
Change-Id: I4928a231495a1295425dc828606b40de03253bab
Signed-off-by: Matthew Barth <msbarth@us.ibm.com>

host-sensors: Reset when system off but last state was on

---

host_reset_recovery.cpp

Mar 09 03:28:22 p10bmc phosphor-host-reset-recovery[587]: Chassis power on has completed, checking if host is still running after the BMC reboot
Mar 09 03:28:22 p10bmc phosphor-host-reset-recovery[587]: Host was not booting before BMC reboot
Mar 09 03:28:22 p10bmc systemd[1]: fsi-scan@0.service: Deactivated successfully.
Mar 09 03:28:22 p10bmc systemd[1]: Stopped Scan FSI devices.

Fix stopFSIScan Dbus call

---

bmc_state_manager.cpp
service_files/phosphor-systemd-target-monitor.service
service_files/xyz.openbmc_project.State.BMC.service
service_files/xyz.openbmc_project.State.Chassis.service
service_files/xyz.openbmc_project.State.Host.service
service_files/xyz.openbmc_project.State.ScheduledHostTransition.service

As more errors are added to state-manager services, need to ensure they
are run after phosphor-logging is up and running. I saw an error path
recently on a BMC reset with the host up scenario where
bmc-state-manager tried to log an error but phosphor-logging was not
running yet, resulting in an unhandled exception.
Tested:
- Verify all state services start after logging (bmc is earliest):
Mar 09 18:40:33 p10bmc systemd[1]: Starting Phosphor Log Manager...
Mar 09 18:40:34 p10bmc systemd[1]: Started Phosphor Log Manager.
Mar 09 18:40:34 p10bmc systemd[1]: Starting Phosphor BMC State Manager...
Mar 09 18:40:35 p10bmc systemd[1]: Started Phosphor BMC State Manager.
- Verify PEL data after all services running:
"User Data 0": {
"Section Version": "1",
"Sub-section type": "1",
"Created by": …

ensure proper phosphor-logging dependencies

---

chassis_state_manager.cpp
chassis_state_manager.hpp

In addition to the uPower interface, monitor the PowerSystemInputs
interface to detect a Brownout condition. Reference:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/48015
Tested: In simulation, trigger a power supply brownout and clear it,
verify that phosphor-chassis-check-power-status detects the condition:
Mar 29 19:02:21 p10bmc phosphor-chassis-state-manager[1101]: Power
System Inputs status changed to
xyz.openbmc_project.State.Decorator.PowerSystemInputs.Status.Fault
Mar 29 19:02:21 p10bmc phosphor-chassis-state-manager[1101]: Power
System Inputs status is in Fault state
root@p10bmc:~# /usr/bin/phosphor-chassis-check-power-status --chassis 0
<3> Chassis power status is not good:
xyz.openbmc_project.State.Chassis.PowerStatus.BrownOut
Mar 29 19:08:20 p10bmc …

chassis: Monitor the PowerSystemInputs for power status

---

chassis_state_manager.cpp

After a power blackout, the power-on LED group, which is asserted when
power is on, would have been restored to still be asserted.  Turn it off
explicitly since the code knows power is now off.
This fixes SW547826
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

Turn off power-on LEDs after a power blackout

---

host_check.cpp

Defect SW548561 showed an issue where host-check did not correctly get
the host state from pldm and assumed the system was off. The journal
logs were inconclusive on where the issue was, but at some point later,
it did appear pldmd was up and running and could talk to the host.
Use this commit to add some additional debug and a few more retries in
this path.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>

host-check: add extra debug and time

---

bmc_state_manager.hpp
chassis_state_manager.cpp
chassis_state_manager.hpp
host_state_manager.hpp
hypervisor_state_manager.hpp
meson.build
scheduled_host_transition.hpp

This directory is created by default on r/r scenarios but on an AC
loss, the directory is not created.
This is downstream only code and fixes SW548523
Tested:
- Verified on AC loss the expected /run/openbmc/chassis@0-lost-power
file is now created and APR logic sees it.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>

ensure /run/openbmc dir created on power loss

---

target_files/meson.build
target_files/obmc-host-graceful-quiesce@.target

Per design here:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/52874
This introduces a new target which can be started to gracefully quiesce
the host. This allows the host an opportunity to shut itself down
gracefully.
Tested:
- Built image with new target and included pldmSoftPowerOff.service in
it so that host firmware got a chance to gracefully shut down prior to
Quiesce.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: I1b5d609b50951e5d529379196c36c0d66e429a8f

host-graceful-quiesce: introduce new target

---

discover_system_state.cpp

Recently code was added to move the vpd collection services to later in
the BMC boot. This caused a conflict with the APR (Automatic Power
Restart) service. The APR service would start the power on of the host
before vpd collection had completed. This caused conflicts on the shared
i2c busses between the BMC and host firmware.
Long term, we need a way to know when the vpd collection services have
completed and APR should not run until the BMC has reached READY state
and the vpd collection has completed.
Short term, add a 30 second delay when APR detects it needs to power on
the system. This ensure APR does not impact the BMC boot when it's not
needed and adds a safe delay when it does need to boot the system.
Tested:
- Powered on p10bmc chassis, caused an AC cycle, and verified that APR …

delay apr power on by 30 seconds

---

host_state_manager.cpp
meson.build
scripts/host-reboot
service_files/phosphor-reboot-host@.service
target_files/obmc-host-quiesce@.target

The host reboot path can be triggered via paths outside of the normal
RequestedHostTransition property set. For example, if the host crashes,
it just triggers an automatic reboot using the systemd targets, which
means the check to prevent continuous host reboots is not run.
This commit ensures we decrement the reboot counter when a host crash
occurs, and it also ensures we check that count when deciding if a
reboot should occur.
While testing, it was found when we end in the host Quiesce state (after
all reboot attempts have expired), the host stayed in Quiesce, even
after issuing a power off. The fix for that was to ensure the
obmc-host-quiesce@.target conflicted with obmc-host-stop@.target to
ensure it would properly run on the power off request and update the
host state to Off.
Tested: …

host-reboot: enforce host boot count on host crash

---

discover_system_state.cpp

In situations where the power restore policy was set to Restore from
the last known state (Restore) and the requested host transition was
not denoted as On would lead to the host never powering back on.
For example, this occurs during a fresh boot of a system or after
completing a system update where other RequestedHostTransition
properties may be set such as 'GracefulWarmReboot'. This lead to the
old logic in discover system state to never power the host back on
which means there was a potential that users would have to manually
power back on the host. This change inverts the logic, essentially
checking to ensure the 'RequestedHostTransition' was not set to off
and therefore indicating that power should be restored in all other
cases (per the interface documentation).
Tested:
- All …

Power restore from last state after AC Loss

---

scripts/host-reboot

This script was introduced to ensure a system properly halted in scenarios where the host has crashed (obmc-host-crash@.target). There was a loophole where the standard reboot attempt logic check was not running in this specific path.
Unfortunately, that original change was not done quite right. This script is actually called on all host reboots so we have run into situations where the host is being put into quiesce before being given one last try to boot. That last try in non-host crash scenarios is where certain recovery actions (like trying alternate boot sources for some devices) is done.
This commit modifies the script to ensure it only moves the host to the quiesce state when the cause of the host reboot was a host crash.
Tested:
- Verified in normal reboot path, even if …

only quiesce in reboot on host crash

---

chassis_state_manager.cpp

When phosphor-chassis-state-manager starts, it makes a D-Bus call to get the Status property of the PowerSystemInputs interface.  This property indicates whether the power supplies are receiving adequate input power.
This D-Bus call can fail due to a timeout.  This occurs when the BMC is heavily loaded, such as when the BMC is rebooted while the chassis is powered on.
If this D-Bus call fails, initially assume the power supply input power is good.  Rely on a PropertiesChanged event for notification if the input power state changes.
Without this commit, a timeout causes the application to exit and the BMC to go into the Quiesced state.
Signed-off-by: Shawn McCarney <shawnmm@us.ibm.com>
Change-Id: I6ad10484a5a9768f2db13b70fb675dd50db4ffda

Handle timeout when getting PowerSystemInputs

---

chassis_state_manager.cpp
host_reset_recovery.cpp
scheduled_host_transition_main.cpp

This is just a rebase with upstream. Not entirely sure why it shows the 2 patches we carry downstream as new (1040 stop fsi scan, Handle timeout...). They are already in the 1050 branch. But maybe with this rebase and PR, it'll make things "right" for future rebases. The only new content is the "scheduled-host-transition" patch which is merged upstream.

1050 sched host fixes

---

host_state_manager.hpp

The default in 1020/1030 code was that any external setting of host reboot attempts (AttemptsLeft) 
would result in setting AttemptsLeft to 3. The design point was that BMC firmware owned the reboot count.
Upstream added Redfish support to set the host reboot count so the design has changed to allow external users to now actually set the AttemptsLeft property.
The issue is that PHYP sends a 0 down via PLDM, expecting the BMC firmware to reset AttemptsLeft to the default (not 0). Long term the PHYP code will need to change to send down the correct AttemptsLeft value but BMC will carry a targeted patch until they are done to ensure the same behavior we had in 1020/1030.
Tested:
- Booted system and verified AttemptsLeft was reset to 3 once PHYP standby was reached.
Signed-off-by: Andrew …

default AttemptsLeft to max when 0 is sent

---

bmc_state_manager.cpp
bmc_state_manager.hpp
chassis_state_manager.cpp
chassis_state_manager.hpp
host_state_manager.cpp
host_state_manager.hpp
utils.cpp
utils.hpp

An issue was recently hit in manufacturing where this call to the
Subscribe method provided by systemd returned a dbus timeout. The
phosphor-host-state-manager service was restarted and the call then
passed, but by this time the first fail generated a core dump
and resulted in a BMC Quiesced state.
No searching of systemd bugs has turned up anything in this area so it
appears to be specific to OpenBMC. Opening a bug against systemd is not
allowed as this was found in our older firmware release which is running
older systemd. There would also be very minimal data to provide systemd.
https://github.com/openbmc/phosphor-state-manager/issues/4 was a similar issue, but in the chassis
state manager. Similar to that situation, a lot was going on with the
BMC at the time of the timeout. In our …

1030 retry subscribe timeouts

---

meson.build
meson_options.txt
secure_boot_check.cpp

Log an error if the TPM measurement fails due to the absence or invalid value of the file '/sys/class/tpm/tpm0/pcr-sha256/0'.
Upstream Commit :
https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/61963
Tested:
Verified that an error is logged when '/sys/class/tpm/tpm0/pcr-sha256/0' is absent, empty, or has a value of 0, indicating that the TPM measurement has failed.
```
"Severity" : {
"type" : "s",
"data" : "xyz.openbmc_project.Logging.Entry.Level.Error"
},
"Message" : {
"type" : "s",
"data" : "xyz.openbmc_project.State.Error.TpmMeasurementFail"
},
"AdditionalData" : {
"type" : "as",
"data" : [
"ERROR=TPM measurement value is empty: /sys/class/tpm/tpm0/pcr-sha256/0",
"_PID=501"
]
},
```

secure-boot: Log an error if TPM measurement fails

---

.gitignore
bmc_state_manager.cpp
chassis_state_manager.cpp
discover_system_state.cpp
host_reset_recovery.cpp
host_state_manager.hpp

As usual, the diff shows more then I'm actually doing here with this upstream rebase for whatever reason. This is just picking up 2 commits:
- https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/64257
- https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/64258

1050 pinhole reset reason first

---

meson.build
meson_options.txt
secure_boot_check.cpp

Perform the TPM Measurement Check only if TPM is present. This commit
adds a new option to provide the sysfs TPM device tree path, which will
be used to verify TPM's presence. If the device tree path doesn't exist,
it indicates that TPM is not present.
Upstream Commit :
https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/65283
Tested: Tested in all three systems
Change-Id: I583355b0677d1377007cf99003c3d9676f445aba

Check the TPM measurement if TPM is present

---

.clang-format
hypervisor_state_manager.hpp

clang-format-17 has some backwards incompatible changes that require additional settings for best compatibility and re-running the formatter. Copy the latest .clang-format from the docs repository and reformat the repository.
Change-Id: I6c35c476f2c7238321c6e9a2662d7f5d4377c64a

clang-format: copy latest and re-format

---

scheduled_host_transition.cpp
service_files/xyz.openbmc_project.State.ScheduledHostTransition.service

This was fixed in upstream code via the introduction of the BMC Ready feature[1]. Backporting all of that function would bring additional risks for our old releases so put a simpler version of it in that will just dealy 60s when the BMC is not at a Ready state.
Tested:
- Set a time that would expire during the BMC reboot and rebooted the BMC. Confirmed code path was hit and power on was delayed by 60s.
[1]: https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/68576

1020:sched-host: add delay when BMC not at ready

---

scheduled_host_transition.cpp
service_files/xyz.openbmc_project.State.ScheduledHostTransition.service

This was fixed in upstream code via the introduction of the BMC Ready feature[1]. Backporting all of that function would bring additional risks for our old releases so put a simpler version of it in that will just dealy 60s when the BMC is not at a Ready state.
Tested:
- Set a time that would expire during the BMC reboot and rebooted the BMC. Confirmed code path was hit and power on was delayed by 60s.
[1]: https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/68576

1030:sched-host: add delay when BMC not at ready

---

target_files/obmc-chassis-poweron@.target
target_files/obmc-host-reboot@.target
target_files/obmc-host-shutdown@.target
target_files/obmc-host-start@.target
target_files/obmc-host-startmin@.target
target_files/obmc-host-stop@.target

This reverts commit b62410b3c209d44086909294c33a60b88f49aeb6.
We finally picked this up in downstream and pretty quickly ran into a couple of issues.
The first was then when hitting an error early in the obmc-chassis-poweron@0.target, we hit situations where the obmc-chassis-poweroff@0.target would be properly triggered during the OnFailure but it would not properly stop the obmc-power-start.service. This caused the subsequent power on to fail because the obmc-power-start.service was considered already running. I dug around for a bit on this but can only conclude we're doing something systemd can not handle (there are a lot of services running in obmc-chassis-poweron@0.target and obmc-chassis-poweroff@0.target).
The second issue is that on IBM systems, the host firmware requests a lot of …

Revert "remove 'flush' failure modes"

---

meson.build
meson.options
redundant-bmc/meson.build
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/meson.build
redundant-bmc/src/rbmc_manager_main.cpp
service_files/meson.build
service_files/xyz.openbmc_project.State.BMC.Redundancy.service

As discussed in the redundant BMC design doc
https://gerrit.openbmc.org/c/openbmc/docs/+/70233, a new application is needed to manage redundant BMC functionality.
This application is called phosphor-rbmc-state-manager, and its compilation is enabled with a 'rbmc-state-management' meson option.  The code is in its own 'redundant-bmc' subdirectory because it will probably be made up of a lot of files, and hopefully have a lot of testcases, by the time it is finished.
It hosts an xyz.openbmc_project.State.BMC.Redundancy interface on a service of the same name, on the /xyz/openbmc_project/state/bmc0 object path.
This commit just gets the application running where it immediately sets its role to Passive and starts up its heartbeat signal, which will eventually be obtained by the sibling to …

RBMC: Introduce RBMC state manager

---

meson.build
redundant-bmc/README.md
redundant-bmc/meson.build
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/meson.build
redundant-bmc/src/rbmc_manager_main.cpp
redundant-bmc/src/role_determination.cpp
redundant-bmc/src/role_determination.hpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp
redundant-bmc/test/meson.build
redundant-bmc/test/role_determination_test.cpp
subprojects/googletest.wrap

At this point, there is only a minimal simulation model, and information about the sibling BMC is not yet available.  What is available is the BMC position, which is set by the simulation startup script by writing a 'bmc_position' udev environment variable:
```
$ fw_printenv bmc_position
bmc_position=0
```
This commit makes use of that variable to determine if it should be Active or Passive, where position zero is for the Active BMC. Eventually this would be replaced by a D-Bus property hosted by some other application.
A Services class was created to obtain that and future system information in a way that can be mocked if necessary for unit testing.
A new role_determination::run() function was created that for now just takes the BMC position value, but in the future will probably need to …

RBMC: Choose role based on position

---

service_files/phosphor-set-chassis-transition-to-off@.service
service_files/phosphor-set-chassis-transition-to-on@.service

If a user were to power their system on, and then off, and then off again, they will see their CurrentPowerState set to TransitioningToOff.
Although it's a bit of an unusual use case, it's fairly common in the lab/dev environment when users want to quickly ensure their system is in a powered off or on state (without first looking at its current state).
Similar to what is in the host transition services, ensure we only run the chassis transition services once per power on or off.
Tested:
- Ensured multiple power off requests will not leave CurrentPowerState in TransitioningToOff state
Change-Id: I4040072ed0b42f37c9488994b0f7a5975a2bb7c9

phosphor-set-chassis-transition: ensure only run once

---

redundant-bmc/README.md
redundant-bmc/src/active_role_handler.cpp
redundant-bmc/src/active_role_handler.hpp
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/meson.build
redundant-bmc/src/passive_role_handler.cpp
redundant-bmc/src/passive_role_handler.hpp
redundant-bmc/src/rbmc_manager_main.cpp
redundant-bmc/src/role_handler.hpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp
target_files/meson.build
target_files/obmc-bmc-active.target
target_files/obmc-bmc-passive.target

After the BMC has determined its role, start the new obmc-bmc-active.target or obmc-bmc-passive.target systemd targets.  In the future, systemd services that only run when the BMC has a certain role can use those.
This class also introduces ActiveRoleHandler and PassiveRoleHandler classes that will house all of the role specific code so that the Manager class doesn't have to handle everything.  The first thing they will do is start their respective targets.
The code waits for the target to finish (or fail) starting because in the case of the active target, redundancy will be enabled after waiting for all of the active services linked to the target to have started.
The two targets conflict with each other, so if the active target is started when the passive one is already running, the …

RBMC: Start systemd targets based on role

---

redundant-bmc/README.md
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/meson.build
redundant-bmc/src/rbmc_manager_main.cpp
redundant-bmc/src/role_determination.cpp
redundant-bmc/src/role_determination.hpp
redundant-bmc/src/sibling.hpp
redundant-bmc/src/sibling_impl.cpp
redundant-bmc/src/sibling_impl.hpp
redundant-bmc/test/role_determination_test.cpp

The first commit starts looking at the xyz.openbmc_project.State.BMC.Redundancy.Sibling D-Bus interface.  It creates a class around it that can provide access to the properties.
The second commit starts using the sibling fields in active vs passive role determination.

RBMC: Start looking at sibling BMC

---

redundant-bmc/src/meson.build
redundant-bmc/src/rbmc_tool.cpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp

This tool can display information about and eventually modify redundant BMC behavior.  The idea is it can be used for lab debug, field debug via capturing output in BMC dumps, and allow changing redundancy behavior for bringup and manufacturing test.
The tool uses a new Services::getFWVersion() function that uses the same hash of the VERSION_ID field in /etc/os-release as used in the sibling application.  This is included so that the version of both the local and sibling BMC can be shown together.  In the future this value will also be used when determining if redundancy can be enabled.
So far, the tool provides:
```
$ rbmctool -h
RBMC Tool
Usage: ./rbmctool [OPTIONS]
Options:
-h,--help                   Print this help message and exit
-d                          Display RBMC Information …
```

RBMC: Add rbmctool executable

---

meson.build

This option should be specified by default so that `meson setup build` can work out-of-the-box, or else the `libgpiod` dependency won't provide `libgpiodcxx`.
Several other repositories are doing this already:
```
$ rg -t meson "bindings=cxx"
host-error-monitor/meson.build
30:  default_options: ['bindings=cxx'],
openpower-vpd-parser/meson.build
121:            default_options: ['bindings=cxx'],
intel-ipmi-oem/meson.build
65:      default_options: ['bindings=cxx'],
openpower-vpd-parser/test/meson.build
16:libgpiodcxx = dependency('libgpiodcxx', default_options: ['bindings=cxx'])
dbus-sensors/meson.build
39:gpiodcxx = dependency('libgpiodcxx', default_options: ['bindings=cxx'])
openpower-proc-control/meson.build
143:libgpiodcxx_dep = dependency('libgpiodcxx', default_options: …
```

phosphor-state-manager: Add -Dbindings=cxx to libgpiod dependency

---

redundant-bmc/src/sibling_impl.cpp

Add the maximum amount of time the BMC will for its sibling to show up to the journal.
Tested:
```
Waiting up to 360s for sibling interface and/or heartbeat: Present = True, Heartbeat = False
```

RBMC: Trace the time to wait for sibling

---

redundant-bmc/src/rbmc_tool.cpp

If the role hasn't been determined yet, then displaying the role reason isn't helpful.
Tested:
No Role:
```
Local BMC
-----------------------------
Role:                Unknown
BMC Position:        1
Redundancy Enabled:  false
BMC State:           Ready
Failovers Paused:    false
FW version hash:     6B442E99
Provisioned:         true
```
Role:
```
Local BMC
-----------------------------
Role:                Active
BMC Position:        1
Redundancy Enabled:  true
BMC State:           Ready
Failovers Paused:    false
FW version hash:     6B442E99
Provisioned:         true
Role Reason:         Resuming previous role
```

RBMC: rbmctool: Don't print RoleReason if no role

---

redundant-bmc/src/active_role_handler.cpp
redundant-bmc/src/active_role_handler.hpp
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/passive_role_handler.cpp
redundant-bmc/src/passive_role_handler.hpp
redundant-bmc/src/redundancy_interface.cpp
redundant-bmc/src/role_handler.hpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp
redundant-bmc/src/sibling.hpp
redundant-bmc/src/sibling_impl.cpp

This PR has 3 commits:
- Mirror the RedundancyEnabled property on the passive BMC
- Add support to read the chassis power state
- Support the DisableRedundancyOverride property so redundancy can be manually disabled

RBMC: Support DisableRedundancyOverride property

---

redundant-bmc/README.md
redundant-bmc/src/active_role_handler.cpp
redundant-bmc/src/active_role_handler.hpp
redundant-bmc/src/sibling.hpp
redundant-bmc/src/sibling_impl.cpp
redundant-bmc/src/timer.hpp

The first commit when will disable redundancy when the passive BMC goes to the Quiesce state.  We could still keep syncs running here if we wanted to.
The second commit disables redundancy when contact with the passive is lost for 5 minutes.  Anytime the passive come back, even if less than 5 minutes, there will be an attempt to re-enabled redundancy, which would include a full sync when available.

RBMC: Take actions on passive BMC failures.

---

redundant-bmc/src/sibling_impl.cpp

The BMC.Redundancy.Sibling interface will be removed from D-Bus when the sibling can no longer be accessed.  This stops the heartbeat, so any functions registered to be called on sibling heartbeat changes must be called.
Tested:
The loss of that interface on D-Bus is now correctly interpreted as a sibling heartbeat loss.

RBMC: Call sibling HB change func on iface removed

---

redundant-bmc/src/rbmc_tool.cpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp

Move this function from rbmc_tool.cpp into the Services class so that the application code can call it.  It will be used in the future when checking to see if a failover is possible.
Tested:
rbmctool still works

RBMC: Move getBMCState call into Services

---

redundant-bmc/src/meson.build
redundant-bmc/src/rbmc_tool.cpp
redundant-bmc/src/sibling_reset.hpp
redundant-bmc/src/sibling_reset_impl.cpp
redundant-bmc/src/sibling_reset_impl.hpp

Add an option to rbmctool to reset the sibling BMC using the reset GPIO.  This reset will also be done during a failover, and the class created to do the reset will also be used in that case.
Note that in the assertReset() and releaseReset() functions the GPIO is not held, so that during real use during a failover if something goes horribly wrong the GPIO won't get stuck being held.
Just a long option was provided to attempt to make it a bit harder to type by accident.
Tested:
New options:
Options:
-h,--help                   Print this help message and exit
-d                          Display RBMC Information
-e Needs: -d                Add extended RBMC details to the display
--reset-sibling             Reset the sibling BMC
The reset:
$ ./rbmctool --reset-sibling
<6> Asserting sibling …

RBMC: Add rbmctool option to reset sibling BMC

---

redundant-bmc/README.md
redundant-bmc/src/passive_role_handler.cpp
redundant-bmc/src/persistent_data.hpp
redundant-bmc/src/redundancy.cpp
redundant-bmc/src/redundancy.hpp
redundant-bmc/src/redundancy_mgr.cpp
redundant-bmc/src/redundancy_mgr.hpp
redundant-bmc/src/services.hpp
redundant-bmc/src/services_impl.cpp
redundant-bmc/src/services_impl.hpp
redundant-bmc/test/redundancy_test.cpp

Whenever an attempt to enable redundancy at runtime is made, redundancy can't be enabled if it wasn't already enabled when runtime was first reached.  An example of when the check would be done is after either BMC comes back from a reboot at runtime.   Implement this check by:
1. Start tracking if  the system is at off/booting/runtime/other.  While this commit only cares about off vs runtime, there will be uses for the other states in the future, such as pausing failovers during those periods.
2.  When the state reaches runtime, save if redundancy is off and also save a 'valid' flag with it.  When the system goes to Off, clear the valid flag so that the code knows the redundancy value isn't usable until the next time runtime is reached.
3. When redundancy is being determined, also check …

Don't enable redundancy at runtime if it wasn't enabled when runtime was first reached.

---

redundant-bmc/src/active_role_handler.cpp
redundant-bmc/src/active_role_handler.hpp
redundant-bmc/src/manager.cpp
redundant-bmc/src/manager.hpp
redundant-bmc/src/passive_role_handler.cpp
redundant-bmc/src/passive_role_handler.hpp
redundant-bmc/src/providers.hpp
redundant-bmc/src/providers_impl.hpp
redundant-bmc/src/rbmc_manager_main.cpp
redundant-bmc/src/redundancy_mgr.cpp
redundant-bmc/src/redundancy_mgr.hpp
redundant-bmc/src/role_handler.hpp

Add a Providers class to manage the various provider helper classes, as there are more coming.  With this, only it has to be created in main(), and only it has to be passed around.

RBMC: Create Providers class to hold the various provider helper classes

---

redundant-bmc/README.md
redundant-bmc/src/persistent_data.hpp
redundant-bmc/src/rbmc_tool.cpp
redundant-bmc/src/redundancy.cpp
redundant-bmc/src/redundancy.hpp
redundant-bmc/src/redundancy_mgr.cpp
redundant-bmc/src/redundancy_mgr.hpp
redundant-bmc/test/redundancy_test.cpp

Add support for calculating FailoversPaused based on the system state.  The code is similar to the code that determines if redundancy can be enabled.

Set FailoversPaused when the system state is not off or runtime
